export const southPoleIds = {
  id: {
    frame: "frame",
    antartic: "antartic",
    antarticIceSurface: "antartic_ice_surface",
    antarticSurface: "antartic_surface",
    antarticCirclePath: "antartic_circle_path",
    routes: "routes",
    scott: "scott",
    scottRouteStart: "scott_route_start",
    scottLabel: "scott_label",
    scottRoute: "scott_route",
    scottCircle: "scott_circle",
    scottBox: "scott_box",
    amundsen: "amundsen",
    amundsenRouteStart: "amundsen_route_start",
    amundsenRoute: "amundsen_route",
    amundsenLabel: "amundsen_label",
    amundsenCircle: "amundsen_circle",
    amundsenBox: "amundsen_box",
    nimrod: "nimrod",
    nimrodRouteStart: "nimrod_route_start",
    nimrodRoute: "nimrod_route",
    nimrodLabel: "nimrod_label",
    nimrodCircle: "nimrod_circle",
    nimrodBox: "nimrod_box",
    discovery: "discovery",
    discoveryRouteStart: "discovery_route_start",
    discoveryRoute: "discovery_route",
    discoveryLabel: "discovery_label",
    discoveryCircle: "discovery_circle",
    discoveryBox: "discovery_box",
    cross: "cross",
    crossRouteStart: "cross_route_start",
    crossRoute: "cross_route",
    crossLabel: "cross_label",
    crossCircle: "cross_circle",
    crossBox: "cross_box",
    belgica: "belgica",
    belgicaRouteStart: "belgica_route_start",
    belgicaRoute: "belgica_route",
    belgicaLabel: "belgica_label",
    belgicaCircle: "belgica_circle",
    belgicaBox: "belgica_box",
    cook: "cook",
    cookRouteStart: "cook_route_start",
    cookRoute: "cook_route",
    cookLabel: "cook_label",
    cookCircle: "cook_circle",
    cookBox: "cook_box",
    caption: "caption",
    captionDescription: "caption_description",
    captionTitle: "caption_title",
    elements: "elements",
    elementsCircleText: "elements_circle_text",
    elementsItemsTextPole: "elements_items_text_pole",
    elementsItemsText2600: "elements_items_text_2600",
    elementsItemsTextCircle: "elements_items_text_circle",
    elementsItemsTextDeg0: "elements_items_text_deg0",
    elementsItemsTextDeg90: "elements_items_text_deg90",
    elementsMountVinson: "elements_mount_vinson",
    elementsMountVinsonLabel: "elements_mount_vinson_label",
    elementsMountVinsonIcon: "elements_mount_vinson_icon",
    elementsMountVinsonBox: "elements_mount_vinson_box",
    elementsMountErebus: "elements_mount_erebus",
    elementsMountErebusLabel: "elements_mount_erebus_label",
    elementsMountErebusIcon: "elements_mount_erebus_icon",
    elementsMountErebusBox: "elements_mount_erebus_box",
    elementsText: "elements_text",
    elementsTextRossIce: "elements_text_ross_ice",
    elementsTextFilchnerRonne: "elements_text_filchner_ronne",
    elementsTextRossSea: "elements_text_ross_sea",
    elementsTextWeddellSea: "elements_text_weddell_sea"
  },
  generators: {
    getRouteLabelId: (id: string) => `${id}_label`,
    getRouteId: (id: string) => `${id}_route`,
    getRouteCircleId: (id: string) => `${id}_circle`,
    getRouteBoxId: (id: string) => `${id}_box`,
    getRouteStartId: (id: string) => `${id}_route_start`,
  }

}
