export const southPoleIds = {
  id: {
    antartic: "antartic",
    antarticIceSurface: "antartic_ice_surface",
    antarticSurface: "antartic_surface",
    antarticCircle: "antartic_circle",
    antarticCircleText: "antartic_circle_text",
    antarticItemsTextPole: "antartic_items_text_pole",
    antarticItemsText2600: "antartic_items_text_2600",
    antarticItemsTextCircle: "antartic_items_text_circle",
    antarticItemsTextDeg0: "antartic_items_text_deg0",
    antarticItemsTextDeg90: "antartic_items_text_deg90",
    antarticCirclePath: "antartic_circle_path",
    antarticMountVinson: "antartic_mount_vinson",
    antarticMountVinsonLabel: "antartic_mount_vinson_label",
    antarticMountVinsonIcon: "antartic_mount_vinson_icon",
    antarticMountVinsonBox: "antartic_mount_vinson_box",
    antarticMountErebus: "antartic_mount_erebus",
    antarticMountErebusLabel: "antartic_mount_erebus_label",
    antarticMountErebusIcon: "antartic_mount_erebus_icon",
    antarticMountErebusBox: "antartic_mount_erebus_box",
    antarticText: "antartic_text",
    antarticTextRossIce: "antartic_text_ross_ice",
    antarticTextFilchnerRonne: "antartic_text_filchner_ronne",
    antarticTextRossSea: "antartic_text_ross_sea",
    antarticTextWeddellSea: "antartic_text_weddell_sea",
    routes: "routes",
    scott: "scott",
    scottRouteStart: "scott_route_start",
    scottLabel: "scott_label",
    scottRoute: "scott_route",
    scottCircle: "scott_circle",
    scottBox: "scott_box",
    amundsen: "amundsen",
    amundsenRouteStart: "amundsen_route_start",
    amundsenRoute: "amundsen_route",
    amundsenLabel: "amundsen_label",
    amundsenCircle: "amundsen_circle",
    amundsenBox: "amundsen_box",
    nimrod: "nimrod",
    nimrodRouteStart: "nimrod_route_start",
    nimrodRoute: "nimrod_route",
    nimrodLabel: "nimrod_label",
    nimrodCircle: "nimrod_circle",
    nimrodBox: "nimrod_box",
    discovery: "discovery",
    discoveryRouteStart: "discovery_route_start",
    discoveryRoute: "discovery_route",
    discoveryLabel: "discovery_label",
    discoveryCircle: "discovery_circle",
    discoveryBox: "discovery_box",
    cross: "cross",
    crossRouteStart: "cross_route_start",
    crossRoute: "cross_route",
    crossLabel: "cross_label",
    crossCircle: "cross_circle",
    crossBox: "cross_box",
    belgica: "belgica",
    belgicaRouteStart: "belgica_route_start",
    belgicaRoute: "belgica_route",
    belgicaLabel: "belgica_label",
    belgicaCircle: "belgica_circle",
    belgicaBox: "belgica_box",
    cook: "cook",
    cookRouteStart: "cook_route_start",
    cookRoute: "cook_route",
    cookLabel: "cook_label",
    cookCircle: "cook_circle",
    cookBox: "cook_box",
    caption: "caption",
    captionDescription: "caption_description",
    captionTitle: "caption_title",
    frame: "frame",
  },
  generators: {
    getRouteLabelId: (id: string) => `${id}_label`,
    getRouteId: (id: string) => `${id}_route`,
    getRouteCircleId: (id: string) => `${id}_circle`,
    getRouteBoxId: (id: string) => `${id}_box`,
    getRouteStartId: (id: string) => `${id}_route_start`,
  }

}
